# Generated by Django 4.2.6 on 2024-09-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('system_name', models.CharField(default='default', max_length=100)),
                ('system_overview', models.CharField(default='default', max_length=1000)),
                ('mail', models.EmailField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, '要望受付'), (1, '制作途中'), (2, '制作完了')], default=0)),
            ],
        ),
    ]
