# Generated by Django 4.2.6 on 2024-07-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='system_name',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
