# Generated by Django 4.2.6 on 2024-07-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
